import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Moda i dobrej jakości ubrania w najlepszej cenie</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/cat2.jpg" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <a>Outella</a>
        </h1>
      <div className={styles.navbar}>
      <div className={styles.navbarRow}><p>Lorem  </p>
      <div className={styles.navbarColumn}><p> </p></div>
      </div>
      
      <div className={styles.navbarRow}><p>ipsum  </p>
      <div className={styles.navbarColumn}><p> </p></div>
      </div>

      <div className={styles.navbarRow}><p>dolor  </p>
      <div className={styles.navbarColumn}><p> </p></div>
      </div>

      <div className={styles.navbarRow}><p>sit  </p>
      <div className={styles.navbarColumn}><p> </p></div>
      </div>

      <div className={styles.navbarRow}><p>amet </p>
      <div className={styles.navbarColumn}><p> </p></div>
      </div>

      </div>
        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
        <a> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur malesuada leo tortor, vitae hendrerit sapien ultrices non. Integer mollis lectus nec massa commodo auctor. Quisque mollis risus in eros gravida. </a>
        <a> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur malesuada leo tortor, vitae hendrerit sapien ultrices non. Integer mollis lectus nec massa commodo auctor. Quisque mollis risus in eros gravida. </a>
        </div>
      </main>

      <footer className={styles.footer}>
       <div className={styles.columns}>
       <div className={styles.rows}><p>Header 1</p></div>
        <div className={styles.rows}><p>Row 1.1 aaaaaaaaaaaaaaa</p></div>
        <div className={styles.rows}><p>Row 1.2 aaaaaaaaaaaaaaa</p></div>
        <div className={styles.rows}><p>Row 1.3 aaaaaaaaaaaaaaa</p></div>
       </div>

       <div className={styles.columns}>
       <div className={styles.rows}><p>Header 2</p></div>
        <div className={styles.rows}><p>Row 2.1 aaaaaaaaaaaaaaa</p></div>
        <div className={styles.rows}><p>Row 2.2 aaaaaaaaaaaaaaa</p></div>
        <div className={styles.rows}><p>Row 2.3 aaaaaaaaaaaaaaa</p></div>
       </div>

       <div className={styles.columns}>
       <div className={styles.rows}><p>Header 3</p></div>
       <div className={styles.rows}><p>Row 3.1 aaaaaaaaaaaaaaa</p></div>
       <div className={styles.rows}><p>Row 3.2 aaaaaaaaaaaaaaa</p></div>
       <div className={styles.rows}><p>Row 3.3 aaaaaaaaaaaaaaa</p></div>
       </div>
      </footer>
    </div>
  )
}
