import styles from "./head.module.css"


export default function Head(){
    return(
        <div className={styles.head}>
        <title>Moda i dobrej jakości ubrania w najlepszej cenie</title> 
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/outella.jpg" />
        <style>
        @import url('https://fonts.googleapis.com/css2?family=Playfair+Display&display=swap');
        </style> 
        </div>
    )
}