import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import NavBar from "../components/navbar";
import Footer from "../components/footer";
import Main_Photos from "../components/main_photos";
import Dresses_Types from "../components/dresses_types"
import Bestsellers from "../components/bestsellers"



export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Moda i dobrej jakości ubrania w najlepszej cenie</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/outella.jpg" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          {" "}
          {/*==================== T I T L E ====================>*/}
          <a>Outella</a>
        </h1>

        <NavBar />

        <p className={styles.description}>"Zdjęcia przykładowe"</p>

        <Main_Photos />

        <p className={styles.description}>"Ikony typów sukien"</p>

        <Dresses_Types />

        <p className={styles.description}>Bestsellery</p>

        <Bestsellers />
      </main>

      <Footer />
    </div>
  )
}
